arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Elias Custom Airplay2 Integration Test
hassio_api: false
boot: auto
image: mikebrady/shairport-sync:latest
init: false
host_network: true
audio: true
name: Elias Custom Shairport-Sync
slug: elias-airplay
url: https://github.com/elias1731/elias-custom-ha-repo/
version: 0.1